### PR TITLE
Logical Operator

### PR DESCRIPTION
**Pull request by jagadyudha**

### CODE REVIEW

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me I will go ahead and merge this. Thank you for your contribution 💯 Feel free to support this repo by leaving a :star: !

**Comment by jagadyudha** [comment]
can you give me hacktoberfest accept label?

**Comment by Rishit-dagli** [comment]
> can you give me hacktoberfest accept label?

@jagadyudha According to the [Hacktoberfest website](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

```
PRs count if:
Submitted during the month of October AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```

Since this PR has been merged the label won't be necessary.

**Comment by Rishit-dagli** [comment]
@all-contributors please add @jagadyudha for code

**Pull request merged**
