### PR TITLE
added ebooks FluentPython and HeadFirstPython

### PR DESCRIPTION
**Pull request by sukhwal13**

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
@sukhwal13 Could you verify that this book is available to distribute freely?

Also, to move forward with this change could you sign the CLA mentioned in [this comment](https://github.com/Rishit-dagli/Python3-by-practice/pull/33#issuecomment-702547061)

**Comment by accyo** [comment]
can we add ebooks in different languages, like Portuguese, Spanish, Italian...?

**Comment by Rishit-dagli** [comment]
> can we add ebooks in different languages, like Portuguese, Spanish, Italian...?

@sukhwal13 Ideally we should allow it, however, I may not be able to review them, so as of now I am giving it second thoughts

**Comment by sukhwal13** [comment]
> @sukhwal13 Could you verify that this book is available to distribute freely?
> 
> Also, to move forward with this change could you sign the CLA mentioned in [this comment](https://github.com/Rishit-dagli/Python3-by-practice/pull/33#issuecomment-702547061)

**Comment by accyo** [comment]
ok (:

**Comment by Rishit-dagli** [comment]
> @sukhwal13 Could you verify that this book is available to distribute freely?
> 
> Also, to move forward with this change could you sign the CLA mentioned in [this comment](https://github.com/Rishit-dagli/Python3-by-practice/pull/33#issuecomment-702547061)

@sukhwal13 This meant you would need to address this comment

**Pull request closed without merging**
