### PR TITLE
Add Python Codecademy Ebook

### PR DESCRIPTION
**Pull request by itsnotsagar**

### CODE REVIEW

**Comment by itsnotsagar** [comment]
@Rishit-dagli check this out. Is this alright?

**Review by Rishit-dagli — CHANGES_REQUESTED** [review]
@itsnotsagar Could you verify that this book is available to distribute freely?

**Comment by itsnotsagar** [comment]
> @itsnotsagar Could you verify that this book is available to distribute freely?
@Rishit-dagli yes it is!

**Review by Rishit-dagli — APPROVED** [review]
@itsnotsagar This looks good to me I will go ahead and merge it. Thank you for your contribution 💯 . Feel free to support this repo by leaving a ⭐ !

**Comment by Rishit-dagli** [comment]
@all-contributors please add @itsnotsagar for content

**Pull request merged**
