### PR TITLE
added neural network ebook

### PR DESCRIPTION
**Pull request by chetak123**
I have added an ebook for making simple neural network (machine learning) according to the issue #12

### CODE REVIEW

**Review by Rishit-dagli — CHANGES_REQUESTED** [review]
Could you verify that the book is available to distribute freely? Also to maintain consistency could you rename the file to `make-your-own-neural-network.pdf`

**Comment by chetak123** [comment]
its available on z-library (free)

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me, I will go ahead and merge it. Thank you for your contribution 💯 Feel free to support this repo by leaving a :star: !

**Comment by Rishit-dagli** [comment]
@all-contributors please add @chetak123 for content

**Pull request merged**
