### PR TITLE
Add ML Cheatsheet in ML folder

### PR DESCRIPTION
**Pull request by manthan89-py**
This cheatsheet available online free. So there is no copyright issue. Very good cheat sheet for ML recap in very few minutes

### CODE REVIEW

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me, I will go ahead and merge it. Thank you for your contribution 💯  Feel free to support this repo by leaving a ⭐ !

**Comment by Rishit-dagli** [comment]
@all-contributors please add @manthan89-py for content

**Comment by manthan89-py** [comment]
Hello Rishit ,
                     I don't understand you want me to tell. And what i
have to do next. I am very new to github. What i want to do with
all-contibutors github page ? Please can you help me

**Comment by manthan89-py** [comment]
I am not receiving any Pull request

**Comment by Rishit-dagli** [comment]
> Hello Rishit , I don't understand you want me to tell. And what i have to do next. I am very new to github. What i want to do with all-contibutors github page ? Please can you help me

@manthan89-py There is nothing more to do from your end, this project uses all-contributors to list you [here](https://github.com/Rishit-dagli/Python3-by-practice#contributors-)

**Comment by Rishit-dagli** [comment]
> I am not receiving any Pull request

About this, a PR was made to add you to README ( #77 ) and was merged but [as told earlier](https://github.com/Rishit-dagli/Python3-by-practice/pull/65#issuecomment-704738845), nothing would be required from your end.

**Pull request merged**
