### PR TITLE
Added Fibonacci Series 

### PR DESCRIPTION
**Pull request by ChiragSaxena5437**
Added Fibonacci Series in Introduction following directory names

### CODE REVIEW

**Comment by ChiragSaxena5437** [comment]
@Rishit-dagli  you can merge this branch directly with the book if you don't find any errors after reviewing the Fibonacci series files.

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli you can merge this branch directly with the book if you don't find any errors after reviewing the Fibonacci series files.

@ChiragSaxena5437 There are a couple of more PRs in the review process, so it might be some time.

**Review by Rishit-dagli — CHANGES_REQUESTED** [review]
I have made a couple of styling changes, not changing the code. Could you also remove the "Learn Python the Hrad Way" book since this PR focusses on the Fibonacci example? Also, in case this problem is taken from some other platform be sure to add a link to the original problem.

**Comment by ChiragSaxena5437** [comment]
I will make a new one Sorry for increasing your work

**Comment by Rishit-dagli** [comment]
> I will make a new one Sorry for increasing your work

@ChiragSaxena5437 I just meant to delete the "Learn Python the Hrad Way" book from your fork and not to close this PR in entirety.

**Pull request closed without merging**
