### PR TITLE
Computer Vision in Python

### PR DESCRIPTION
**Pull request by gpriya32**

### CODE REVIEW

**Review by Rishit-dagli — COMMENTED** [review]
@gpriya32 Can you verify that this book is available to distribute freely?

**Comment by gpriya32** [comment]
Yes, @Rishit-dagli it is available online as pdf for learners.

**Comment by gpriya32** [comment]
http://programmingcomputervision.com/downloads/ProgrammingComputerVision_CCdraft.pdf
You can check here.

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me I will go ahead and merge this. Thank you for your contribution :100: Feel free to support this repo by leaving a :star: !

**Comment by Rishit-dagli** [comment]
@all-contributors please add @gpriya32 for content

**Pull request merged**
