### PR TITLE
added ebook

### PR DESCRIPTION
**Pull request by cocobaco**
added ebook 'a byte of python'

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
@cocobaco Could you verify that the books are available to distribute freely?

**Comment by cocobaco** [comment]
yes it's free. https://python.swaroopch.com/

**Review by Rishit-dagli — APPROVED** [review]
@cocobaco This looks good to me I will go ahead and merge it. Thank you for your contribution 💯 . Feel free to support this repo by leaving a ⭐ !

**Comment by Rishit-dagli** [comment]
@all-contributors please add @cocobaco for content

**Pull request merged**
