### PR TITLE
Book added

### PR DESCRIPTION
**Pull request by Avinashshah099**
Deep-Learning-with-Pytorch is added

### CODE REVIEW

**Review by Rishit-dagli — COMMENTED** [review]
@Avinashshah099 Could you verify that this book is available to distribute freely?

**Comment by Avinashshah099** [comment]
Yes, it is freely available at pytorch site.

**Comment by Rishit-dagli** [comment]
@Avinashshah099 This looks like a great addition to me, I will merge this. Thanks a lot for the contribution! 💯

**Comment by Rishit-dagli** [comment]
@all-contributors please add @Avinashshah099 for content

**Pull request merged**
