### PR TITLE
Add Project Euler on problem-6

### PR DESCRIPTION
**Pull request by sujoy-coder**
Hello Sir,
First of all I am a beginner in open source contribution. So In this section I have made a little contribution on Project Euler. I hope you like it and give me an approval for HacktoberFest-2020 event. 

Thank You ...

### CODE REVIEW

**Review by Rishit-dagli — CHANGES_REQUESTED** [review]
It seems that you have removed the README file in entirety could you fix that?

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me I will go ahead and merge it. Thank you for your contribution :100: . Feel free to support this repo by leaving a :star: !

**Comment by sujoy-coder** [comment]
Thank You sir :)

**Comment by Rishit-dagli** [comment]
@all-contributors please add @sujoy-coder for code

**Comment by Rishit-dagli** [comment]
@all-contributors please add @sujoy-coder for code

**Pull request merged**
