### PR TITLE
Added Python Cheat Sheet

### PR DESCRIPTION
**Pull request by kushalbargoti**
This PDF contains cheat sheet for python.

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
@kushalbargoti Since this cheat sheet is created by Datacamp, could you verify if it is made available to distribute freely?

**Comment by kushalbargoti** [comment]
@Rishit-dagli  Yes, they have provided various cheat sheets publicly and I have found this one useful.

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me, I will merge this. Thank you for this contribution 💯

**Comment by Rishit-dagli** [comment]
@all-contributors please add @kushalbargoti for content

**Pull request merged**
