### PR TITLE
Machine Learning Algorithms image

### PR DESCRIPTION
**Pull request by Avinashshah099**

### CODE REVIEW

**Review by Rishit-dagli — COMMENTED** [review]
@Avinashshah099 Can you verify that this is a non-copyrighted document and is availaible to distribute freely

**Comment by Avinashshah099** [comment]
Yes, it is freely available at machine learning mastery

**Comment by Rishit-dagli** [comment]
> Yes, it is freely available at machine learning mastery

Could you also verify if it's not copyrighted?

**Comment by Avinashshah099** [comment]
It is not copyrighted.

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me, I will go ahead and merge it. Thank you for your contribution 💯

**Pull request merged**
