### PR TITLE
Added an ML project

### PR DESCRIPTION
**Pull request by mihikachh22**
Hey There,
Using Python3 I have created a project implementing Machine Learning on Fraud Detection Analysis

### CODE REVIEW

**Comment by mihikachh22** [comment]
Hey there,
There are so many mails from your side. Could you please summarize and
tell, what is to be done in the project. It will be of great help.
Thank you

**Comment by Rishit-dagli** [comment]
> Hey there, There are so many mails from your side. Could you please summarize and tell, what is to be done in the project. It will be of great help. Thank you

@mihikachh22 You can see all the required changes in the comments, these can also bee seen on GitHub itself
- https://github.com/Rishit-dagli/Python3-by-practice/pull/29#issuecomment-702571172
- https://github.com/Rishit-dagli/Python3-by-practice/pull/29#issuecomment-702571176

**Comment by mihikachh22** [comment]
I am not able to understand the stale concept. Could you please elaborate?

**Comment by Rishit-dagli** [comment]
> I am not able to understand the stale concept. Could you please elaborate?

@mihikachh22 Having stale bots are pretty common, it is used to draw attention towards important PRs on which the contributors are intending to work on. Since you haven't written any comment or made the required changes for 2 weeks the PR was marked as stale. You can know more about why having Stale Issues and PRs is bad for repo in [this article](https://www.edwardthomson.com/blog/github_actions_8_stale_issues_and_pull_requests.html).

**Pull request closed without merging**
