### PR TITLE
Basic Python Summery Note Added for absolute beginners

### PR DESCRIPTION
**Pull request by mihinduranasinghe**
Basic python cheat sheet for absolute beginners

### CODE REVIEW

**Comment by mihinduranasinghe** [comment]
Can you please approve this pull request with hactoberfest label

**Review by Rishit-dagli — CHANGES_REQUESTED** [review]
For consistency could you rename the file to `Basic Python.ipynb` and place it in the root folder instead. Also, could you follow the [Guidelines for Jupyter Notebooks](https://github.com/Rishit-dagli/Python3-by-practice/issues/12)

**Comment by mihinduranasinghe** [comment]
I updated it by changing file name to Basin Python.ipynb and placed it in root.

**Comment by Rishit-dagli** [comment]
> I updated it by changing file name to Basin Python.ipynb and placed it in root.

Could you follow the [Guidelines for Jupyter Notebooks](https://github.com/Rishit-dagli/Python3-by-practice/issues/12)

**Comment by mihinduranasinghe** [comment]
Updated

**Pull request closed without merging**
