### PR TITLE
Adding book in Machine learning folder (The hundred Page of ML Book)

### PR DESCRIPTION
**Pull request by manthan89-py**

### CODE REVIEW

**Comment by manthan89-py** [comment]
Ok I have done it

**Comment by Rishit-dagli** [comment]
@manthan89-py Could you verify that this book is available to distribute freely?

**Comment by manthan89-py** [comment]
No this Book is paid and This pdf version is not officially disturibute by
author. I am so sorry I don't know about it.I will share another resources
to your repo.

**Comment by Rishit-dagli** [comment]
> No this Book is paid and This pdf version is not officially disturibute by author. I am so sorry I don't know about it.I will share another resources to your repo.

@manthan89-py In that case I would have to close the PR, however, you are more than welcome to contribute to this repo in any other manner 💯 Feel free to support this repo by leaving a ⭐

**Pull request closed without merging**
