### PR TITLE
Added K-Nearest Neighbor(KNN) sample dataset

### PR DESCRIPTION
**Pull request by Avinashshah099**
Added KNN intro file, image and uploaded dataset. I will add the example file too within 24 hrs.

### CODE REVIEW

**Comment by Avinashshah099** [comment]
Can you give me code to generate buttons in the notebook?

**Comment by Avinashshah099** [comment]
@Rishit-dagli, Can you give me code to generate buttons in the notebook?

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli, Can you give me code to generate buttons in the notebook?

It seems you haven't added a notebook. Once you add a notebook I will add the notebook buttons myself.

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me I will go ahead and merge it. Thank you for your contribution 💯 . Feel free to support this repo by leaving a ⭐ !

**Comment by Avinashshah099** [comment]
@Rishit-dagli Can you give me code to generate buttons, so that I can submit the notebook? I have already built the notebook, waiting for buttons.

**Comment by Rishit-dagli** [comment]
@all-contributors please add @Avinashshah099 for code

**Pull request merged**
