### PR TITLE
Added Python for Data Analysis by Wes McKinneythat I found helpful.

### PR DESCRIPTION
**Pull request by ChiragSaxena5437**
Python for Data Analysis-Wes McKinney

### CODE REVIEW

**Comment by ChiragSaxena5437** [comment]
@Rishit-dagli please check I have reviewed and please confirm if I can some other books and blogs on data learning in python

**Review by Rishit-dagli — COMMENTED** [review]
@ChiragSaxena5437 Could you verify that this book is available to distribute freely?

**Comment by ChiragSaxena5437** [comment]
@Rishit-dagli  Yes the book is available on many sites like https://bedford-computing.co.uk/learning/wp-content/uploads/2015/10/Python-for-Data-Analysis.pdf and many other sites of technological institutes. Also can you confirm me about the vlog.

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli please check I have reviewed and please confirm if I can some other books and blogs on data learning in python

Yes, you can add other books and blogs

**Review by Rishit-dagli — APPROVED** [review]
This looks good to me, I will go ahead and merge this. Thank you for your contribution 💯 Feel free to support this repo by leaving a ⭐ !

**Comment by Rishit-dagli** [comment]
@all-contributors please add @ChiragSaxena5437 for content

**Pull request merged**
